name: nightly
on:
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: read

jobs:
  setup-without:
    runs-on: ubuntu-latest
    steps:
      - name: ci/test
        run: echo "test"
  setup:
    if: ${{ github.event_name != 'schedule' && (github.ref_name  == 'master' || github.ref_name  == 'main') }}
    runs-on: ubuntu-latest
    steps:
      - name: ci/test
        run: echo "test"
